# ---------- Stage 1: Build ----------
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build


# ---------- Stage 2: Export build ----------
FROM alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist